version: "3"

services:
  server-service:
    build: ./server
    volumes:
      - ./server:/usr/app
    ports:
      - 3001:3001
  client:
    image: react:webapp
    build: ./client
    volumes:
      - ./client:/usr/app
    ports:
      - 3000:3000
