version: "3"

services:
  server-service:
    container_name: server
    build: ./server
    hostname: server
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    ports:
      - 3001:3001
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - 27107:27107
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000

volumes:
  data:
