const ACTIONS = {
  EMPLOYEE_HOURS_GET_ALL: "EMPLOYEE_HOURS_GET_ALL",
  EMPLOYEE_HOURS_SET_ALL: "EMPLOYEE_HOURS_SET_ALL",
  EMPLOYEE_HOURS_DELETE_BY_ID: "EMPLOYEE_HOURS_DELETE_BY_ID",
  EMPLOYEE_HOURS_UPDATE_BY_ID: "EMPLOYEE_HOURS_UPDATE_BY_ID",
  DATE_PANEL_CHANGE_DATE: "DATE_PANEL_CHANGE_DATE",
};

export { ACTIONS };
