const ACTIONS = {
  EMPLOYEE_HOURS_GET_ALL: "EMPLOYEE_HOURS_GET_ALL",
  EMPLOYEE_HOURS_SET_ALL: "EMPLOYEE_HOURS_SET_ALL",
  EMPLOYEE_HOURS_DELETE_BY_ID: "EMPLOYEE_HOURS_DELETE_BY_ID",
};

export { ACTIONS };
